! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Auxiliary Routines File
!
! Generated by KPP-2.5.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Harvard University, USA
!        H. Lin,      Harvard University, USA
!        R. Yantosca, Harvard University, USA
!
! File                 : gckpp_Util.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Util

  USE gckpp_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! UTIL - Utility functions
!   Arguments :
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!
! InitSaveData - Opens the data file for writing
!   Parameters :
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE gckpp_Parameters

      open(10, file='gckpp.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!
! SaveData - Write LOOKAT species in the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE gckpp_Global
      USE gckpp_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
      (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
 999  FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!
! CloseSaveData - Close the data file
!   Parameters :
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE gckpp_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!
! GenerateMatlab - Generates MATLAB file to load the data file
!   Parameters :
!                It will have a character string to prefix each
!                species name with.
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE gckpp_Parameters
      USE gckpp_Global
      USE gckpp_Monitor


      CHARACTER(LEN=8) PREFIX
      INTEGER i

      open(20, file='gckpp.m')
      write(20,*) 'load gckpp.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = gckpp;')
      write(20,*) 'clear gckpp;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do

      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! ****************************************************************
!
! Integrator_Update_Options - determine whether to call Update_RCONST,
!    Update_PHOTO, and Update_SUN from within the integrator
!
!   Parameters:
!    option (input)
!        = -1 :  Do not call Update_* functions within the integrator
!        =  0 :  Status quo: Call whichever functions are normally called
!        =  1 :  Call Update_RCONST from within the integrator
!        =  2 :  Call Update_PHOTO from within the integrator
!        =  3 :  Call Update_RCONST and Update_PHOTO from within the int.
!        =  4 :  Call Update_SUN from within the integrator
!        =  5 :  Call Update_SUN and Update_RCONST from within the int.
!        =  6 :  not implemented
!        =  7 :  not implemented
!
!    Do_Update_RCONST (output):
!        =T : Calls Update_RCONST from within the integrator
!        =F : Does not call UPDATE_RCONST from w/in the int.
!
!    Do_Update_PHOTO (output):
!        =T : Calls Update_PHOTO from within the integrator
!        =F : Does not call UPDATE_PHOTO from w/in the int.
!
!    Do_Update_SUN (output):
!        =T : Calls Update_SUN from within the integrator
!        =F : Does not call UPDATE_SUN from w/in the int.
!
! ****************************************************************

      SUBROUTINE Integrator_Update_Options( option,            &
                                            Do_Update_RConst,  &
                                            Do_Update_Photo,   &
                                            Do_Update_Sun     )

      !~~~> Input variables
      INTEGER, INTENT(IN)  :: option

      !~~~> Output variables
      LOGICAL, INTENT(OUT) :: Do_Update_RCONST
      LOGICAL, INTENT(OUT) :: Do_Update_PHOTO
      LOGICAL, INTENT(OUT) :: Do_Update_SUN

      ! Option -1: turn off all Update_* calls within the integrator
      IF ( option == -1 ) THEN
         Do_Update_RCONST = .FALSE.
         Do_Update_PHOTO  = .FALSE.
         Do_Update_SUN    = .FALSE.
         RETURN
      ENDIF

      ! Otherwise determine from the value passed
      Do_Update_RCONST = ( IAND( option, 1 ) > 0 )
      Do_Update_PHOTO  = ( IAND( option, 2 ) > 0 )
      Do_Update_SUN    = ( IAND( option, 4 ) > 0 )

      END SUBROUTINE Integrator_Update_Options

! End of Integrator_Update_Options function
! ****************************************************************
! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(261) = V_USER(1)
  V(247) = V_USER(2)
  V(240) = V_USER(3)
  V(6) = V_USER(4)
  V(289) = V_USER(5)
  V(132) = V_USER(6)
  V(7) = V_USER(7)
  V(206) = V_USER(8)
  V(183) = V_USER(9)
  V(173) = V_USER(10)
  V(276) = V_USER(11)
  V(221) = V_USER(12)
  V(281) = V_USER(13)
  V(121) = V_USER(14)
  V(75) = V_USER(15)
  V(184) = V_USER(16)
  V(215) = V_USER(17)
  V(125) = V_USER(18)
  V(297) = V_USER(19)
  V(154) = V_USER(20)
  V(160) = V_USER(21)
  V(62) = V_USER(22)
  V(200) = V_USER(23)
  V(300) = V_USER(24)
  V(15) = V_USER(25)
  V(311) = V_USER(26)
  V(302) = V_USER(27)
  V(204) = V_USER(28)
  V(87) = V_USER(29)
  V(115) = V_USER(30)
  V(47) = V_USER(31)
  V(48) = V_USER(32)
  V(1) = V_USER(33)
  V(49) = V_USER(34)
  V(2) = V_USER(35)
  V(50) = V_USER(36)
  V(51) = V_USER(37)
  V(69) = V_USER(38)
  V(95) = V_USER(39)
  V(185) = V_USER(40)
  V(149) = V_USER(41)
  V(170) = V_USER(42)
  V(167) = V_USER(43)
  V(58) = V_USER(44)
  V(59) = V_USER(45)
  V(61) = V_USER(46)
  V(64) = V_USER(47)
  V(65) = V_USER(48)
  V(66) = V_USER(49)
  V(67) = V_USER(50)
  V(68) = V_USER(51)
  V(93) = V_USER(52)
  V(94) = V_USER(53)
  V(3) = V_USER(54)
  V(4) = V_USER(55)
  V(5) = V_USER(56)
  V(290) = V_USER(57)
  V(258) = V_USER(58)
  V(120) = V_USER(59)
  V(52) = V_USER(60)
  V(219) = V_USER(61)
  V(118) = V_USER(62)
  V(55) = V_USER(63)
  V(211) = V_USER(64)
  V(90) = V_USER(65)
  V(91) = V_USER(66)
  V(304) = V_USER(67)
  V(220) = V_USER(68)
  V(92) = V_USER(69)
  V(259) = V_USER(70)
  V(287) = V_USER(71)
  V(303) = V_USER(72)
  V(123) = V_USER(73)
  V(286) = V_USER(74)
  V(8) = V_USER(75)
  V(133) = V_USER(76)
  V(106) = V_USER(77)
  V(159) = V_USER(78)
  V(233) = V_USER(79)
  V(84) = V_USER(80)
  V(146) = V_USER(81)
  V(100) = V_USER(82)
  V(126) = V_USER(83)
  V(203) = V_USER(84)
  V(239) = V_USER(85)
  V(129) = V_USER(86)
  V(9) = V_USER(87)
  V(260) = V_USER(88)
  V(246) = V_USER(89)
  V(201) = V_USER(90)
  V(70) = V_USER(91)
  V(56) = V_USER(92)
  V(57) = V_USER(93)
  V(312) = V_USER(94)
  V(236) = V_USER(95)
  V(274) = V_USER(96)
  V(309) = V_USER(97)
  V(217) = V_USER(98)
  V(116) = V_USER(99)
  V(113) = V_USER(100)
  V(114) = V_USER(101)
  V(98) = V_USER(102)
  V(147) = V_USER(103)
  V(148) = V_USER(104)
  V(99) = V_USER(105)
  V(76) = V_USER(106)
  V(305) = V_USER(107)
  V(235) = V_USER(108)
  V(131) = V_USER(109)
  V(134) = V_USER(110)
  V(135) = V_USER(111)
  V(136) = V_USER(112)
  V(139) = V_USER(113)
  V(77) = V_USER(114)
  V(78) = V_USER(115)
  V(42) = V_USER(116)
  V(79) = V_USER(117)
  V(43) = V_USER(118)
  V(80) = V_USER(119)
  V(85) = V_USER(120)
  V(101) = V_USER(121)
  V(102) = V_USER(122)
  V(103) = V_USER(123)
  V(216) = V_USER(124)
  V(288) = V_USER(125)
  V(122) = V_USER(126)
  V(314) = V_USER(127)
  V(284) = V_USER(128)
  V(295) = V_USER(129)
  V(292) = V_USER(130)
  V(157) = V_USER(131)
  V(212) = V_USER(132)
  V(143) = V_USER(133)
  V(214) = V_USER(134)
  V(141) = V_USER(135)
  V(151) = V_USER(136)
  V(152) = V_USER(137)
  V(195) = V_USER(138)
  V(293) = V_USER(139)
  V(166) = V_USER(140)
  V(53) = V_USER(141)
  V(60) = V_USER(142)
  V(41) = V_USER(143)
  V(88) = V_USER(144)
  V(197) = V_USER(145)
  V(218) = V_USER(146)
  V(119) = V_USER(147)
  V(264) = V_USER(148)
  V(174) = V_USER(149)
  V(230) = V_USER(150)
  V(127) = V_USER(151)
  V(153) = V_USER(152)
  V(169) = V_USER(153)
  V(256) = V_USER(154)
  V(190) = V_USER(155)
  V(191) = V_USER(156)
  V(188) = V_USER(157)
  V(267) = V_USER(158)
  V(171) = V_USER(159)
  V(155) = V_USER(160)
  V(253) = V_USER(161)
  V(156) = V_USER(162)
  V(252) = V_USER(163)
  V(140) = V_USER(164)
  V(244) = V_USER(165)
  V(165) = V_USER(166)
  V(168) = V_USER(167)
  V(238) = V_USER(168)
  V(268) = V_USER(169)
  V(269) = V_USER(170)
  V(245) = V_USER(171)
  V(213) = V_USER(172)
  V(207) = V_USER(173)
  V(208) = V_USER(174)
  V(210) = V_USER(175)
  V(150) = V_USER(176)
  V(10) = V_USER(177)
  V(71) = V_USER(178)
  V(271) = V_USER(179)
  V(270) = V_USER(180)
  V(205) = V_USER(181)
  V(175) = V_USER(182)
  V(251) = V_USER(183)
  V(117) = V_USER(184)
  V(225) = V_USER(185)
  V(294) = V_USER(186)
  V(104) = V_USER(187)
  V(11) = V_USER(188)
  V(12) = V_USER(189)
  V(248) = V_USER(190)
  V(192) = V_USER(191)
  V(176) = V_USER(192)
  V(237) = V_USER(193)
  V(266) = V_USER(194)
  V(277) = V_USER(195)
  V(13) = V_USER(196)
  V(14) = V_USER(197)
  V(196) = V_USER(198)
  V(249) = V_USER(199)
  V(16) = V_USER(200)
  V(17) = V_USER(201)
  V(18) = V_USER(202)
  V(19) = V_USER(203)
  V(22) = V_USER(204)
  V(23) = V_USER(205)
  V(26) = V_USER(206)
  V(25) = V_USER(207)
  V(27) = V_USER(208)
  V(28) = V_USER(209)
  V(275) = V_USER(210)
  V(231) = V_USER(211)
  V(161) = V_USER(212)
  V(273) = V_USER(213)
  V(86) = V_USER(214)
  V(285) = V_USER(215)
  V(158) = V_USER(216)
  V(187) = V_USER(217)
  V(223) = V_USER(218)
  V(199) = V_USER(219)
  V(255) = V_USER(220)
  V(229) = V_USER(221)
  V(164) = V_USER(222)
  V(250) = V_USER(223)
  V(105) = V_USER(224)
  V(257) = V_USER(225)
  V(291) = V_USER(226)
  V(243) = V_USER(227)
  V(54) = V_USER(228)
  V(202) = V_USER(229)
  V(224) = V_USER(230)
  V(162) = V_USER(231)
  V(177) = V_USER(232)
  V(89) = V_USER(233)
  V(30) = V_USER(234)
  V(178) = V_USER(235)
  V(179) = V_USER(236)
  V(272) = V_USER(237)
  V(142) = V_USER(238)
  V(193) = V_USER(239)
  V(209) = V_USER(240)
  V(254) = V_USER(241)
  V(265) = V_USER(242)
  V(228) = V_USER(243)
  V(180) = V_USER(244)
  V(81) = V_USER(245)
  V(44) = V_USER(246)
  V(72) = V_USER(247)
  V(198) = V_USER(248)
  V(21) = V_USER(249)
  V(73) = V_USER(250)
  V(74) = V_USER(251)
  V(307) = V_USER(252)
  V(299) = V_USER(253)
  V(310) = V_USER(254)
  V(234) = V_USER(255)
  V(107) = V_USER(256)
  V(20) = V_USER(257)
  V(315) = V_USER(258)
  V(296) = V_USER(259)
  V(308) = V_USER(260)
  V(128) = V_USER(263)
  V(82) = V_USER(264)
  V(313) = V_USER(265)
  V(108) = V_USER(266)
  V(242) = V_USER(267)
  V(241) = V_USER(268)
  V(263) = V_USER(269)
  V(83) = V_USER(270)
  V(144) = V_USER(271)
  V(262) = V_USER(272)
  V(145) = V_USER(273)
  V(232) = V_USER(274)
  V(137) = V_USER(275)
  V(63) = V_USER(276)
  V(226) = V_USER(277)
  V(222) = V_USER(278)
  V(282) = V_USER(279)
  V(138) = V_USER(280)
  V(124) = V_USER(281)
  V(280) = V_USER(282)
  V(227) = V_USER(283)
  V(279) = V_USER(284)
  V(109) = V_USER(285)
  V(110) = V_USER(286)
  V(111) = V_USER(287)
  V(283) = V_USER(288)
  V(278) = V_USER(289)
  V(181) = V_USER(290)
  V(186) = V_USER(291)
  V(194) = V_USER(292)
  V(189) = V_USER(293)
  V(182) = V_USER(294)
  V(112) = V_USER(295)
  V(172) = V_USER(296)
  V(163) = V_USER(297)
  V(298) = V_USER(298)
  V(301) = V_USER(299)
  V(45) = V_USER(304)
  V(306) = V_USER(305)
  V(46) = V_USER(306)
  V(130) = V_USER(307)
  V(31) = V_USER(308)
  V(32) = V_USER(309)
  V(33) = V_USER(310)
  V(96) = V_USER(311)
  V(24) = V_USER(312)
  V(97) = V_USER(313)
  V(29) = V_USER(314)

END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(261)
  V_USER(2) = V(247)
  V_USER(3) = V(240)
  V_USER(4) = V(6)
  V_USER(5) = V(289)
  V_USER(6) = V(132)
  V_USER(7) = V(7)
  V_USER(8) = V(206)
  V_USER(9) = V(183)
  V_USER(10) = V(173)
  V_USER(11) = V(276)
  V_USER(12) = V(221)
  V_USER(13) = V(281)
  V_USER(14) = V(121)
  V_USER(15) = V(75)
  V_USER(16) = V(184)
  V_USER(17) = V(215)
  V_USER(18) = V(125)
  V_USER(19) = V(297)
  V_USER(20) = V(154)
  V_USER(21) = V(160)
  V_USER(22) = V(62)
  V_USER(23) = V(200)
  V_USER(24) = V(300)
  V_USER(25) = V(15)
  V_USER(26) = V(311)
  V_USER(27) = V(302)
  V_USER(28) = V(204)
  V_USER(29) = V(87)
  V_USER(30) = V(115)
  V_USER(31) = V(47)
  V_USER(32) = V(48)
  V_USER(33) = V(1)
  V_USER(34) = V(49)
  V_USER(35) = V(2)
  V_USER(36) = V(50)
  V_USER(37) = V(51)
  V_USER(38) = V(69)
  V_USER(39) = V(95)
  V_USER(40) = V(185)
  V_USER(41) = V(149)
  V_USER(42) = V(170)
  V_USER(43) = V(167)
  V_USER(44) = V(58)
  V_USER(45) = V(59)
  V_USER(46) = V(61)
  V_USER(47) = V(64)
  V_USER(48) = V(65)
  V_USER(49) = V(66)
  V_USER(50) = V(67)
  V_USER(51) = V(68)
  V_USER(52) = V(93)
  V_USER(53) = V(94)
  V_USER(54) = V(3)
  V_USER(55) = V(4)
  V_USER(56) = V(5)
  V_USER(57) = V(290)
  V_USER(58) = V(258)
  V_USER(59) = V(120)
  V_USER(60) = V(52)
  V_USER(61) = V(219)
  V_USER(62) = V(118)
  V_USER(63) = V(55)
  V_USER(64) = V(211)
  V_USER(65) = V(90)
  V_USER(66) = V(91)
  V_USER(67) = V(304)
  V_USER(68) = V(220)
  V_USER(69) = V(92)
  V_USER(70) = V(259)
  V_USER(71) = V(287)
  V_USER(72) = V(303)
  V_USER(73) = V(123)
  V_USER(74) = V(286)
  V_USER(75) = V(8)
  V_USER(76) = V(133)
  V_USER(77) = V(106)
  V_USER(78) = V(159)
  V_USER(79) = V(233)
  V_USER(80) = V(84)
  V_USER(81) = V(146)
  V_USER(82) = V(100)
  V_USER(83) = V(126)
  V_USER(84) = V(203)
  V_USER(85) = V(239)
  V_USER(86) = V(129)
  V_USER(87) = V(9)
  V_USER(88) = V(260)
  V_USER(89) = V(246)
  V_USER(90) = V(201)
  V_USER(91) = V(70)
  V_USER(92) = V(56)
  V_USER(93) = V(57)
  V_USER(94) = V(312)
  V_USER(95) = V(236)
  V_USER(96) = V(274)
  V_USER(97) = V(309)
  V_USER(98) = V(217)
  V_USER(99) = V(116)
  V_USER(100) = V(113)
  V_USER(101) = V(114)
  V_USER(102) = V(98)
  V_USER(103) = V(147)
  V_USER(104) = V(148)
  V_USER(105) = V(99)
  V_USER(106) = V(76)
  V_USER(107) = V(305)
  V_USER(108) = V(235)
  V_USER(109) = V(131)
  V_USER(110) = V(134)
  V_USER(111) = V(135)
  V_USER(112) = V(136)
  V_USER(113) = V(139)
  V_USER(114) = V(77)
  V_USER(115) = V(78)
  V_USER(116) = V(42)
  V_USER(117) = V(79)
  V_USER(118) = V(43)
  V_USER(119) = V(80)
  V_USER(120) = V(85)
  V_USER(121) = V(101)
  V_USER(122) = V(102)
  V_USER(123) = V(103)
  V_USER(124) = V(216)
  V_USER(125) = V(288)
  V_USER(126) = V(122)
  V_USER(127) = V(314)
  V_USER(128) = V(284)
  V_USER(129) = V(295)
  V_USER(130) = V(292)
  V_USER(131) = V(157)
  V_USER(132) = V(212)
  V_USER(133) = V(143)
  V_USER(134) = V(214)
  V_USER(135) = V(141)
  V_USER(136) = V(151)
  V_USER(137) = V(152)
  V_USER(138) = V(195)
  V_USER(139) = V(293)
  V_USER(140) = V(166)
  V_USER(141) = V(53)
  V_USER(142) = V(60)
  V_USER(143) = V(41)
  V_USER(144) = V(88)
  V_USER(145) = V(197)
  V_USER(146) = V(218)
  V_USER(147) = V(119)
  V_USER(148) = V(264)
  V_USER(149) = V(174)
  V_USER(150) = V(230)
  V_USER(151) = V(127)
  V_USER(152) = V(153)
  V_USER(153) = V(169)
  V_USER(154) = V(256)
  V_USER(155) = V(190)
  V_USER(156) = V(191)
  V_USER(157) = V(188)
  V_USER(158) = V(267)
  V_USER(159) = V(171)
  V_USER(160) = V(155)
  V_USER(161) = V(253)
  V_USER(162) = V(156)
  V_USER(163) = V(252)
  V_USER(164) = V(140)
  V_USER(165) = V(244)
  V_USER(166) = V(165)
  V_USER(167) = V(168)
  V_USER(168) = V(238)
  V_USER(169) = V(268)
  V_USER(170) = V(269)
  V_USER(171) = V(245)
  V_USER(172) = V(213)
  V_USER(173) = V(207)
  V_USER(174) = V(208)
  V_USER(175) = V(210)
  V_USER(176) = V(150)
  V_USER(177) = V(10)
  V_USER(178) = V(71)
  V_USER(179) = V(271)
  V_USER(180) = V(270)
  V_USER(181) = V(205)
  V_USER(182) = V(175)
  V_USER(183) = V(251)
  V_USER(184) = V(117)
  V_USER(185) = V(225)
  V_USER(186) = V(294)
  V_USER(187) = V(104)
  V_USER(188) = V(11)
  V_USER(189) = V(12)
  V_USER(190) = V(248)
  V_USER(191) = V(192)
  V_USER(192) = V(176)
  V_USER(193) = V(237)
  V_USER(194) = V(266)
  V_USER(195) = V(277)
  V_USER(196) = V(13)
  V_USER(197) = V(14)
  V_USER(198) = V(196)
  V_USER(199) = V(249)
  V_USER(200) = V(16)
  V_USER(201) = V(17)
  V_USER(202) = V(18)
  V_USER(203) = V(19)
  V_USER(204) = V(22)
  V_USER(205) = V(23)
  V_USER(206) = V(26)
  V_USER(207) = V(25)
  V_USER(208) = V(27)
  V_USER(209) = V(28)
  V_USER(210) = V(275)
  V_USER(211) = V(231)
  V_USER(212) = V(161)
  V_USER(213) = V(273)
  V_USER(214) = V(86)
  V_USER(215) = V(285)
  V_USER(216) = V(158)
  V_USER(217) = V(187)
  V_USER(218) = V(223)
  V_USER(219) = V(199)
  V_USER(220) = V(255)
  V_USER(221) = V(229)
  V_USER(222) = V(164)
  V_USER(223) = V(250)
  V_USER(224) = V(105)
  V_USER(225) = V(257)
  V_USER(226) = V(291)
  V_USER(227) = V(243)
  V_USER(228) = V(54)
  V_USER(229) = V(202)
  V_USER(230) = V(224)
  V_USER(231) = V(162)
  V_USER(232) = V(177)
  V_USER(233) = V(89)
  V_USER(234) = V(30)
  V_USER(235) = V(178)
  V_USER(236) = V(179)
  V_USER(237) = V(272)
  V_USER(238) = V(142)
  V_USER(239) = V(193)
  V_USER(240) = V(209)
  V_USER(241) = V(254)
  V_USER(242) = V(265)
  V_USER(243) = V(228)
  V_USER(244) = V(180)
  V_USER(245) = V(81)
  V_USER(246) = V(44)
  V_USER(247) = V(72)
  V_USER(248) = V(198)
  V_USER(249) = V(21)
  V_USER(250) = V(73)
  V_USER(251) = V(74)
  V_USER(252) = V(307)
  V_USER(253) = V(299)
  V_USER(254) = V(310)
  V_USER(255) = V(234)
  V_USER(256) = V(107)
  V_USER(257) = V(20)
  V_USER(258) = V(315)
  V_USER(259) = V(296)
  V_USER(260) = V(308)
  V_USER(263) = V(128)
  V_USER(264) = V(82)
  V_USER(265) = V(313)
  V_USER(266) = V(108)
  V_USER(267) = V(242)
  V_USER(268) = V(241)
  V_USER(269) = V(263)
  V_USER(270) = V(83)
  V_USER(271) = V(144)
  V_USER(272) = V(262)
  V_USER(273) = V(145)
  V_USER(274) = V(232)
  V_USER(275) = V(137)
  V_USER(276) = V(63)
  V_USER(277) = V(226)
  V_USER(278) = V(222)
  V_USER(279) = V(282)
  V_USER(280) = V(138)
  V_USER(281) = V(124)
  V_USER(282) = V(280)
  V_USER(283) = V(227)
  V_USER(284) = V(279)
  V_USER(285) = V(109)
  V_USER(286) = V(110)
  V_USER(287) = V(111)
  V_USER(288) = V(283)
  V_USER(289) = V(278)
  V_USER(290) = V(181)
  V_USER(291) = V(186)
  V_USER(292) = V(194)
  V_USER(293) = V(189)
  V_USER(294) = V(182)
  V_USER(295) = V(112)
  V_USER(296) = V(172)
  V_USER(297) = V(163)
  V_USER(298) = V(298)
  V_USER(299) = V(301)
  V_USER(304) = V(45)
  V_USER(305) = V(306)
  V_USER(306) = V(46)
  V_USER(307) = V(130)
  V_USER(308) = V(31)
  V_USER(309) = V(32)
  V_USER(310) = V(33)
  V_USER(311) = V(96)
  V_USER(312) = V(24)
  V_USER(313) = V(97)
  V_USER(314) = V(29)

END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)


END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! ComputeFamilies - function to calculate user-defined Prod/Loss families
!   Arguments :
!      V         - Concentrations of variable species (local)
!      FAM       - Accumulated user-defined prod/loss families.
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE ComputeFamilies ( V, FAM )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! FAM - Accumulated user-defined prod/loss families.
  REAL(kind=dp) :: FAM(NFAM)


! Computation of prod/loss families
  FAM(1) = V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)&
             &+0.15*V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+2*V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)&
             &+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(36)+V(34)+V(34)&
             &+V(34)+V(36)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(36)+V(34)+V(36)+V(34)+V(34)+V(36)+V(34)+V(34)+V(34)+V(34)&
             &+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(36)+V(34)&
             &+0.69*V(34)+V(34)+V(34)+V(34)+0.438*V(34)+0.13*V(36)+V(36)+V(34)+V(36)+0.13*V(34)+V(34)+V(36)+0.02*V(34)+0.13&
             &*V(34)+0.995*V(34)+V(34)+V(34)+0.15*V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+2*V(34)+V(34)+0.3*V(34)+V(34)&
             &+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+V(34)+0.00999999*V(34)
  FAM(2) = V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+2*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+2*V(35)+V(35)+2*V(35)+2*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+0.93*V(35)+V(39)&
             &+V(39)+V(39)+2*V(35)+V(35)+V(35)+2*V(35)+V(35)+2*V(35)+2*V(35)+V(35)+V(35)+2*V(35)+V(35)+0.67*V(35)+0.65*V(35)&
             &+0.56*V(35)+0.17*V(35)+0.35*V(35)+0.75*V(35)+0.65*V(35)+0.55*V(35)+0.3*V(35)+0.25*V(35)+0.72*V(35)+0.5*V(35)&
             &+0.1*V(35)+0.11*V(35)+0.55*V(35)+0.7*V(35)+0.08*V(35)+0.2*V(35)+0.16*V(35)+0.12*V(35)+0.04*V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+V(35)+2*V(35)+2*V(35)+2*V(35)+2*V(35)+2*V(35)+2*V(35)+2*V(35)+2*V(35)+V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+2*V(35)+2*V(35)+V(35)+V(35)+0.00100005*V(35)&
             &+5.96046e-08*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+1.258*V(35)+1.5*V(35)+V(35)+1.5&
             &*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+0.5*V(35)+V(35)+2*V(35)+2*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+2*V(35)+2*V(35)+2*V(35)+3*V(35)+3*V(35)+3*V(35)+4*V(35)+4*V(35)+4&
             &*V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)&
             &+V(35)+V(35)+V(35)+V(35)+V(35)+V(35)+2*V(35)+V(35)+V(35)+V(35)+V(35)+2*V(35)+V(35)+2*V(35)+V(35)+V(35)+2*V(35)
  FAM(3) = V(36)+V(36)+0.05*V(36)+0.56*V(36)+0.505*V(36)+V(36)+2*V(36)+V(36)+2*V(36)+V(36)+0.5*V(36)+V(36)+V(36)+V(36)&
             &+V(36)+V(36)+V(36)+V(36)+0.14*V(40)+0.14*V(40)+0.14*V(40)+0.407*V(40)+0.6*V(36)+0.9*V(36)+0.6*V(36)+0.9*V(36)&
             &+V(36)+V(36)+V(36)+0.5*V(36)+0.5*V(36)+0.55*V(36)+0.55*V(36)+0.45*V(36)+0.37*V(36)+0.42*V(36)+0.23*V(36)+0.638&
             &*V(36)+1.5*V(36)+V(36)+0.25*V(36)+0.33*V(36)+0.036*V(36)+0.054*V(36)+V(36)+0.13*V(36)+0.2*V(36)+V(36)+0.2&
             &*V(36)+0.13*V(36)+0.52*V(36)+0.8*V(36)+2*V(36)+0.6*V(36)+0.6*V(36)+0.539*V(36)+0.33*V(36)+0.33*V(36)+0.18&
             &*V(40)+0.036*V(36)+0.12*V(36)+0.68*V(36)+0.77*V(36)+0.25*V(36)+0.75*V(36)+V(36)+2*V(36)+0.84*V(36)+0.507*V(36)&
             &+0.325*V(36)+0.488*V(36)+V(36)+0.86*V(36)+0.65*V(36)+0.25*V(36)+V(36)+0.888*V(36)+V(36)+V(36)+0.364*V(36)+0.2&
             &*V(36)+0.27*V(36)+0.3*V(36)+0.25*V(36)+0.5*V(36)+0.25*V(36)+0.5*V(36)+V(36)+V(36)+0.88*V(36)+V(36)+V(36)+V(36)&
             &+V(36)+2*V(36)+2*V(36)+V(36)+V(36)+V(36)+V(36)+V(36)+V(36)+V(36)+V(36)+V(36)+0.5*V(36)+0.571*V(36)+0.875*V(36)&
             &+0.77*V(36)+V(36)+V(36)+0.888*V(36)+0.818*V(36)+V(36)+V(36)+0.55*V(36)+0.55*V(36)+0.839*V(36)+V(36)+0.122&
             &*V(36)+V(36)+V(36)+V(36)+V(36)
  FAM(4) = V(37)+V(37)+V(37)
  FAM(5) = V(38)+V(38)+V(38)+V(38)+2*V(38)+V(38)+V(38)+V(38)
  FAM(6) = V(39)+V(39)+V(39)+V(39)+V(39)
  FAM(7) = V(40)+V(40)+0.06*V(40)+0.06*V(40)+V(40)+0.02*V(40)+0.02*V(40)+0.02*V(40)+0.013*V(40)+0.045*V(40)

END SUBROUTINE ComputeFamilies

! End of ComputeFamilies function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! Get_OHreactivity - returns the OH reactivity
! The OH reactivity is defined as the inverse of its lifetime.
! This routine was auto-generated using script OHreact_parser.py.
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Get_OHreactivity ( CC, RR, OHreact )

! CC - Concentrations of species (local)
  REAL(kind=dp) :: CC(NSPEC)
! RR - reaction rates (local)
  REAL(kind=dp) :: RR(NREACT)
! OHreact - OH reactivity [s-1]
  REAL(kind=dp) :: OHreact

  OHreact = RR(12)*CC(103) + RR(14)*CC(308) + 2*RR(18) + 2*RR(19) + RR(20)*CC(314) &
          + RR(21)*CC(236) + RR(24)*CC(286) + RR(25)*CC(211) + RR(31)*CC(291) + RR(32)*CC(162) &
          + RR(33)*CC(162) + RR(34)*CC(221) + RR(35)*CC(221) + RR(36)*CC(290) + RR(37)*CC(299) &
          + RR(38)*CC(288) + RR(39)*CC(307) + RR(40)*CC(216) + RR(43)*CC(122) + RR(46)*CC(310) &
          + RR(49)*CC(235) + RR(50)*CC(243) + RR(53)*CC(289) + RR(58)*CC(185) + RR(62)*CC(149) &
          + RR(63)*CC(149) + RR(67)*CC(132) + RR(77)*CC(227) + RR(78)*CC(240) + RR(79)*CC(283) &
          + RR(84)*CC(247) + RR(93)*CC(250) + RR(103)*CC(159) + RR(104)*CC(182) + RR(114)*CC(282) &
          + RR(116)*CC(260) + RR(117)*CC(260) + RR(119)*CC(246) + RR(120)*CC(257) + RR(123)*CC(274) &
          + RR(124)*CC(274) + RR(131)*CC(138) + RR(132)*CC(129) + RR(133)*CC(110) + RR(134)*CC(111) &
          + RR(135)*CC(109) + RR(136)*CC(112) + RR(137)*CC(137) + RR(138)*CC(26) + RR(139)*CC(86) &
          + RR(164)*CC(106) + RR(165)*CC(106) + RR(167)*CC(306) + RR(171)*CC(309) + RR(176)*CC(154) &
          + RR(179)*CC(300) + RR(188)*CC(90) + RR(189)*CC(93) + RR(190)*CC(120) + RR(203)*CC(316) &
          + RR(204)*CC(315) + RR(209)*CC(82) + RR(267)*CC(220) + RR(269)*CC(303) + RR(270)*CC(303) &
          + RR(271)*CC(128) + RR(272)*CC(92) + RR(273)*CC(305) + RR(274)*CC(295) + RR(275)*CC(259) &
          + RR(276)*CC(287) + RR(277)*CC(118) + RR(278)*CC(94) + RR(279)*CC(91) + RR(280)*CC(52) &
          + RR(281)*CC(98) + RR(282)*CC(113) + RR(283)*CC(114) + RR(284)*CC(116) + RR(285)*CC(147) &
          + RR(286)*CC(148) + RR(287)*CC(99) + RR(288)*CC(76) + RR(289)*CC(131) + RR(290)*CC(134) &
          + RR(291)*CC(135) + RR(292)*CC(136) + RR(293)*CC(139) + RR(294)*CC(77) + RR(295)*CC(78) &
          + RR(296)*CC(42) + RR(297)*CC(79) + RR(298)*CC(43) + RR(299)*CC(80) + RR(373)*CC(166) &
          + RR(374)*CC(85) + RR(375)*CC(292) + RR(382)*CC(55) + RR(383)*CC(233) + RR(384)*CC(222) &
          + RR(398)*CC(178) + RR(399)*CC(179) + RR(409)*CC(196) + RR(417)*CC(145) + RR(431)*CC(202) &
          + RR(432)*CC(224) + RR(438)*CC(157) + RR(439)*CC(105) + RR(440)*CC(100) + RR(441)*CC(104) &
          + RR(442)*CC(107) + RR(444)*CC(248) + RR(445)*CC(248) + RR(446)*CC(248) + RR(447)*CC(248) &
          + RR(474)*CC(212) + RR(475)*CC(214) + RR(476)*CC(151) + RR(477)*CC(152) + RR(478)*CC(217) &
          + RR(479)*CC(197) + RR(480)*CC(127) + RR(481)*CC(181) + RR(482)*CC(181) + RR(483)*CC(186) &
          + RR(484)*CC(186) + RR(485)*CC(181) + RR(486)*CC(186) + RR(487)*CC(194) + RR(488)*CC(189) &
          + RR(501)*CC(140) + RR(502)*CC(155) + RR(503)*CC(155) + RR(504)*CC(156) + RR(505)*CC(156) &
          + RR(524)*CC(165) + RR(525)*CC(165) + RR(526)*CC(168) + RR(527)*CC(168) + RR(528)*CC(244) &
          + RR(529)*CC(244) + RR(530)*CC(238) + RR(531)*CC(238) + RR(532)*CC(244) + RR(533)*CC(238) &
          + RR(571)*CC(205) + RR(572)*CC(175) + RR(573)*CC(205) + RR(574)*CC(175) + RR(575)*CC(175) &
          + RR(576)*CC(205) + RR(577)*CC(175) + RR(578)*CC(175) + RR(587)*CC(264) + RR(588)*CC(264) &
          + RR(591)*CC(267) + RR(594)*CC(272) + RR(596)*CC(275) + RR(597)*CC(275) + RR(600)*CC(265) &
          + RR(601)*CC(254) + RR(602)*CC(255) + RR(603)*CC(223) + RR(604)*CC(199) + RR(611)*CC(187) &
          + RR(612)*CC(180) + RR(613)*CC(142) + RR(614)*CC(209) + RR(615)*CC(193) + RR(616)*CC(158) &
          + RR(622)*CC(161) + RR(634)*CC(177) + RR(635)*CC(102) + RR(636)*CC(230) + RR(637)*CC(153) &
          + RR(638)*CC(169) + RR(639)*CC(188) + RR(640)*CC(237) + RR(641)*CC(266) + RR(643)*CC(124) &
          + RR(644)*CC(101) + RR(646)*CC(195) + RR(647)*CC(195) + RR(648)*CC(21) + RR(652)*CC(95) &
          + RR(653)*CC(69) + RR(660)*CC(84) + RR(661)*CC(146) + RR(662)*CC(146) + RR(663)*CC(75) &
          + RR(664)*CC(96) + RR(665)*CC(97) + RR(671)*CC(144) + RR(673)*CC(133) + RR(675)*CC(164) &
          + RR(678)*CC(121) + RR(683)*CC(87) + RR(685)*CC(115) + RR(690)*CC(125) + RR(693)*CC(234) &
          + RR(697)*CC(183) + RR(700)*CC(173) + RR(719)*CC(298) + RR(720)*CC(301)

END SUBROUTINE Get_OHreactivity
! End of Get_OHreactivity subroutine
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE gckpp_Util
